[[figtree]]
arch = "x86_64"
git-tree-sha1 = "3306e91d9b27b34aa9406b764a1b8590c4420761"
libc = "glibc"
os = "linux"

    [[figtree.download]]
    sha256 = "d9fa65de6686099b1cde4b406ea0359214bd0fb20462b642cc0935a771fbf1b2"
    url = "https://github.com/pseastham/StokesParticlesBuilder/releases/download/figtree-v1.0.0+0/figtree.v1.0.0.x86_64-linux-gnu.tar.gz"
