[[figtree]]
arch = "x86_64"
git-tree-sha1 = "2a0e964c9ec3da71732bfb18998398496cf9c439"
libc = "glibc"
os = "linux"

    [[figtree.download]]
    sha256 = "9af89ec2a1a87e500790ea8add2bcbc0f6178c009af422f345a25a57db7c19f2"
    url = "https://github.com/pseastham/StokesParticlesBuilder/releases/download/figtree-v1.1.0+0/figtree.v1.1.0.x86_64-linux-gnu.tar.gz"
