[[figtree]]
arch = "x86_64"
git-tree-sha1 = "ab471d61722acb8580f6509e1c31da1ed967d3de"
libc = "glibc"
os = "linux"

    [[figtree.download]]
    sha256 = "0c75a955a50005ba9b97518a4ea209c5922d63155fe6af770ae3e4fea888d7c3"
    url = "https://github.com/pseastham/StokesParticlesBuilder/releases/download/figtree-v1.0.0+0/figtree.v1.0.0.x86_64-linux-gnu.tar.gz"
